# Web data getting for actor and director for those 7 moives

## Part 1 : for box office data for actor and director

In [1]:
import lxml.html as lx
import pandas as pd
import requests
import requests_cache
import re
import requests
import requests_ftp
import requests_cache
import lxml
from bs4 import BeautifulSoup
from collections import Counter
from matplotlib import pyplot as plt
import pandas as pd
plt.style.use('ggplot')
requests_cache.install_cache('coll_cache')
%matplotlib inline

By using the methods of beautiful soup to arrive at the desired location of the wanted data on the webpage.

In [14]:
def myfun(urlbase):
    #urlbase = "https://www.the-numbers.com/person/25200401-D-J-Caruso#tab=summary"
    want1= requests.get(urlbase)
    want2 =want1.text
    want3 =BeautifulSoup(want2,'lxml-xml')
    want4=want3.find_all(href=re.compile("box-office-star-record"))
    result1=set([want4[i].text for x in want4 for i in range(0,len(want4))])
    want5=want3.find_all(align=re.compile("right"))
    result2=[want5[i].text for x in want4 for i in range(0,len(want5))][0:len(result1)]
    '''here, result1 and 2 is actually not useful anymore since we can get the whole table in the below functions to obtain the all-aspects data from the websites'''
    want6=want3.find_all(name="td",attrs={'class':'alnright'})
    result3=[want6[i].text for x in want6 for i in range(1,4)][0:3]
    return result3

In [15]:
def myfun1(url):
    '''this function is used for getting the data for specific study for actor and director'''
    url = 'https://www.the-numbers.com/person/25200401-D-J-Caruso#tab=summary'
    res = requests.get(url)
    soup = BeautifulSoup(res.text, 'lxml')
    tables = soup.select('table')
    df_list = []
    for table in tables:
        df_list.append(pd.read_html(table.prettify()))
    m=df_list[2][0]
    return m

box office data for director

In [16]:
link=["https://www.the-numbers.com/person/25200401-D-J-Caruso#tab=summary",
      "https://www.the-numbers.com/person/205050401-Dean-Devlin#tab=summary",
      "https://www.the-numbers.com/person/57580401-F-Gary-Gray#tab=summary",
      "https://www.the-numbers.com/person/80570401-Alex-Kurtzman#tab=summary",
      "https://www.the-numbers.com/person/11530401-Michael-Bay#tab=summary",
      "https://www.the-numbers.com/person/465430401-Jordan-Vogt-Roberts#tab=summary",
      "https://www.the-numbers.com/person/60610401-Lasse-HallstrA-m#tab=summary"]
Domestic=[]
International=[]
Worldwide=[]
for l in link:
    x=myfun(l)
    d=x[0]
    i=x[1]
    w=x[2]
    Domestic.append(d)
    International.append(i) 
    Worldwide.append(w)

In [17]:
Name=["xXx: Return of Xander Cage",
      "Geostorm",
      "The Fate of the Furious",
      "The Mummy",
      "Transformers: The Last Knight",
      "Kong: Skull Island",
      "A Dog’s Purpose"]
dict={'Name':Name,
      'Domestic(director)':Domestic,
      'International(director)':International,
      'Worldwide(director)':Worldwide}
director=pd.DataFrame(dict)
director=director[['Name', 'Domestic(director)', 'International(director)','Worldwide(director)']]
director

,Name,Domestic(director),International(director),Worldwide(director)
0,xXx: Return of Xander Cage,"$341,032,453","$545,426,963","$886,459,416"
1,Geostorm,"$809,318,256","$1,480,685,100","$2,290,003,356"
2,The Fate of the Furious,"$757,018,128","$1,241,886,899","$1,998,905,027"
3,The Mummy,"$1,738,416,625","$2,258,987,757","$3,997,404,382"
4,Transformers: The Last Knight,"$1,255,682,482","$1,587,645,612","$2,843,328,094"
5,Kong: Skull Island,"$169,368,312","$393,132,024","$562,500,336"
6,A Dog’s Purpose,"$529,512,669","$523,863,020","$1,053,375,689"

In [26]:
'''output to csv file'''
director.to_csv('director.csv',index=False)

box office data for actor

In [19]:
myfun("https://www.the-numbers.com/person/39880401-Vin-Diesel#tab=summary")
myfun("https://www.the-numbers.com/person/155860401-Donnie-Yen#tab=summary")
myfun("https://www.the-numbers.com/person/22060401-Gerard-Butler")
myfun("https://www.the-numbers.com/person/1159650401-Talitha-Bateman")
myfun("https://www.the-numbers.com/person/39880401-Vin-Diesel")
myfun("https://www.the-numbers.com/person/72720401-Dwayne-Johnson")
myfun("https://www.the-numbers.com/person/540401-Tom-Cruise")
myfun("https://www.the-numbers.com/person/487260401-Annabelle-Wallis")
myfun("https://www.the-numbers.com/person/1650401-Mark-Wahlberg#tab=summary")
myfun("https://www.the-numbers.com/person/80850401-Shia-LaBeouf#tab=summary")
myfun("https://www.the-numbers.com/person/82280401-Brie-Larson#tab=summary")
myfun("https://www.the-numbers.com/person/670401-Samuel-L-Jackson#tab=summary")
myfun("https://www.the-numbers.com/person/11530401-Michael-Bay#tab=summary")
myfun("https://www.the-numbers.com/person/60610401-Lasse-HallstrA-m#tab=summary")

['$529,512,669', '$523,863,020', '$1,053,375,689']

In [21]:
Actor=["https://www.the-numbers.com/person/39880401-Vin-Diesel#tab=summary",
"https://www.the-numbers.com/person/155860401-Donnie-Yen#tab=summary",
"https://www.the-numbers.com/person/22060401-Gerard-Butler",
"https://www.the-numbers.com/person/1159650401-Talitha-Bateman",
"https://www.the-numbers.com/person/39880401-Vin-Diesel",
"https://www.the-numbers.com/person/72720401-Dwayne-Johnson",
"https://www.the-numbers.com/person/540401-Tom-Cruise",
"https://www.the-numbers.com/person/487260401-Annabelle-Wallis",
"https://www.the-numbers.com/person/1650401-Mark-Wahlberg#tab=summary",
"https://www.the-numbers.com/person/80850401-Shia-LaBeouf#tab=summary",
"https://www.the-numbers.com/person/82280401-Brie-Larson#tab=summary",
"https://www.the-numbers.com/person/670401-Samuel-L-Jackson#tab=summary",
"https://www.the-numbers.com/person/11530401-Michael-Bay#tab=summary",
"https://www.the-numbers.com/person/60610401-Lasse-HallstrA-m#tab=summary"]

In [22]:
Domestic=[]
International=[]
Worldwide=[]
for l in Actor:
    x=myfun(l)
    d=x[0]
    i=x[1]
    w=x[2]
    Domestic.append(d)
    International.append(i) 
    Worldwide.append(w)

In [23]:
Name=["xXx: Return of Xander Cage",
      "xXx: Return of Xander Cage",
      "Geostorm",
      "Geostorm",
      "The Fate of the Furious",
      "The Fate of the Furious",
      "The Mummy",
      "The Mummy",
      "Transformers: The Last Knight",
      "Transformers: The Last Knight",
      "Kong: Skull Island",
      "Kong: Skull Island",
      "A Dog’s Purpose",
      "A Dog’s Purpose"]

In [24]:
dict={'Name':Name,
      'Domestic(actor)':Domestic,
      'International(actor)':International,
      'Worldwide(actor)':Worldwide}
Actor=pd.DataFrame(dict)
Actor=Actor[['Name', 'Domestic(actor)', 'International(actor)','Worldwide(actor)']]
Actor

,Name,Domestic(actor),International(actor),Worldwide(actor)
0,xXx: Return of Xander Cage,"$1,323,338,433","$3,830,289,378","$5,153,627,811"
1,xXx: Return of Xander Cage,$0,"$25,040,000","$25,040,000"
2,Geostorm,"$292,683,312","$283,633,664","$576,316,976"
3,Geostorm,$0,$0,"$33,700,160"
4,The Fate of the Furious,"$1,323,338,433","$3,830,289,378","$5,153,627,811"
5,The Fate of the Furious,"$100,990,648","$133,450,656","$234,441,304"
6,The Mummy,"$1,284,826,648","$2,552,489,126","$3,837,315,774"
7,The Mummy,$0,$0,"$80,101,125"
8,Transformers: The Last Knight,"$492,869,237","$234,728,472","$727,597,709"
9,Transformers: The Last Knight,$0,$0,$0
10,Kong: Skull Island,$0,$0,$0
11,Kong: Skull Island,"$689,602","$218,124","$907,726"
12,A Dog’s Purpose,"$1,255,682,482","$1,587,645,612","$2,843,328,094"
13,A Dog’s Purpose,"$529,512,669","$523,863,020","$1,053,375,689"

In [25]:
'''output to csv file'''
Actor.to_csv('Actor.csv',index=False)

## Part 2  :detailed data for director and actor

for overall analyzing about director

In [138]:
DJ_data=myfun1('https://www.the-numbers.com/person/25200401-D-J-CarusoD-J-Caruso#tab=summary')[1:]

In [139]:
DD_data=myfun1("https://www.the-numbers.com/person/205050401-Dean-Devlin#tab=summary")[1:]

In [140]:
FG_data=myfun1("https://www.the-numbers.com/person/57580401-F-Gary-Gray#tab=summary")[1:]

In [141]:
AK_data=myfun1("https://www.the-numbers.com/person/80570401-Alex-Kurtzman#tab=summary")[1:]

In [142]:
MB_data=myfun1("https://www.the-numbers.com/person/465430401-Jordan-Vogt-Roberts#tab=summary")[1:]

In [143]:
LH_data=myfun1("https://www.the-numbers.com/person/60610401-Lasse-HallstrA-m#tab=summary")[1:]

In [144]:
DD_data.columns=["record","rank","value"]
DJ_data.columns=["record","rank","value"]
FG_data.columns=["record","rank","value"]
AK_data.columns=["record","rank","value"]
MB_data.columns=["record","rank","value"]
LH_data.columns=["record","rank","value"]

In [145]:
directordata=pd.concat([DD_data,DJ_data,FG_data,AK_data,MB_data,LH_data])
# director_data=DD_data
directordata = directordata.reset_index()
directordata=directordata.drop('index',1)
directordata

                                               record  rank         value
0   Top Grossing Associate Producer at the Domesti...   886   $30,038,362
1   Top Grossing Director at the Domestic Box Offi...   228  $341,032,453
2   Top Grossing Executive Producer at the Domesti...  3005    $8,087,783
3   Top Grossing Producer at the Domestic Box Offi...  1771   $28,607,015
4   Top Grossing Screenwriter at the Domestic Box ...  2547    $2,423,467
5   Top Grossing Director at the International Box...   159  $545,426,963
6   Top Grossing Screenwriter at the International...  3085      $721,221
7   Top Grossing Associate Producer at the Worldwi...  1007   $30,038,362
8   Top Grossing Director at the Worldwide Box Off...   175  $886,459,416
9   Top Grossing Executive Producer at the Worldwi...  3524    $8,087,783
10  Top Grossing Producer at the Worldwide Box Off...  2273   $28,607,015
11  Top Grossing Screenwriter at the Worldwide Box...  3157    $3,144,688
12  Top Grossing Associate Producer at the Domesti...   886   $30,038,362
13  Top Grossing Director at the Domestic Box Offi...   228  $341,032,453
14  Top Grossing Executive Producer at the Domesti...  3005    $8,087,783
15  Top Grossing Producer at the Domestic Box Offi...  1771   $28,607,015
16  Top Grossing Screenwriter at the Domestic Box ...  2547    $2,423,467
17  Top Grossing Director at the International Box...   159  $545,426,963
18  Top Grossing Screenwriter at the International...  3085      $721,221
19  Top Grossing Associate Producer at the Worldwi...  1007   $30,038,362
20  Top Grossing Director at the Worldwide Box Off...   175  $886,459,416
21  Top Grossing Executive Producer at the Worldwi...  3524    $8,087,783
22  Top Grossing Producer at the Worldwide Box Off...  2273   $28,607,015
23  Top Grossing Screenwriter at the Worldwide Box...  3157    $3,144,688
24  Top Grossing Associate Producer at the Domesti...   886   $30,038,362
25  Top Grossing Director at the Domestic Box Offi...   228  $341,032,453
26  Top Grossing Executive Producer at the Domesti...  3005    $8,087,783
27  Top Grossing Producer at the Domestic Box Offi...  1771   $28,607,015
28  Top Grossing Screenwriter at the Domestic Box ...  2547    $2,423,467
29  Top Grossing Director at the International Box...   159  $545,426,963
..                                                ...   ...           ...
42  Top Grossing Screenwriter at the International...  3085      $721,221
43  Top Grossing Associate Producer at the Worldwi...  1007   $30,038,362
44  Top Grossing Director at the Worldwide Box Off...   175  $886,459,416
45  Top Grossing Executive Producer at the Worldwi...  3524    $8,087,783
46  Top Grossing Producer at the Worldwide Box Off...  2273   $28,607,015
47  Top Grossing Screenwriter at the Worldwide Box...  3157    $3,144,688
48  Top Grossing Associate Producer at the Domesti...   886   $30,038,362
49  Top Grossing Director at the Domestic Box Offi...   228  $341,032,453
50  Top Grossing Executive Producer at the Domesti...  3005    $8,087,783
51  Top Grossing Producer at the Domestic Box Offi...  1771   $28,607,015
52  Top Grossing Screenwriter at the Domestic Box ...  2547    $2,423,467
53  Top Grossing Director at the International Box...   159  $545,426,963
54  Top Grossing Screenwriter at the International...  3085      $721,221
55  Top Grossing Associate Producer at the Worldwi...  1007   $30,038,362
56  Top Grossing Director at the Worldwide Box Off...   175  $886,459,416
57  Top Grossing Executive Producer at the Worldwi...  3524    $8,087,783
58  Top Grossing Producer at the Worldwide Box Off...  2273   $28,607,015
59  Top Grossing Screenwriter at the Worldwide Box...  3157    $3,144,688
60  Top Grossing Associate Producer at the Domesti...   886   $30,038,362
61  Top Grossing Director at the Domestic Box Offi...   228  $341,032,453
62  Top Grossing Executive Producer at the Domesti...  3005    $8,087,783
63  Top Grossing Producer at the Domestic Box Offi...  1771   $28,607,015
64  Top Grossing Screenwriter at the Domestic Box ...  2547    $2,423,467
65  Top Grossing Director at the International Box...   159  $545,426,963
66  Top Grossing Screenwriter at the International...  3085      $721,221
67  Top Grossing Associate Producer at the Worldwi...  1007   $30,038,362
68  Top Grossing Director at the Worldwide Box Off...   175  $886,459,416
69  Top Grossing Executive Producer at the Worldwi...  3524    $8,087,783
70  Top Grossing Producer at the Worldwide Box Off...  2273   $28,607,015
71  Top Grossing Screenwriter at the Worldwide Box...  3157    $3,144,688

[72 rows x 3 columns]

In [146]:
m1=["D-J-Caruso"]*12
m2=["Dean-Devlin"]*12
m3=["F-Gary"]*12
m4=["Alex-Kurtzman"]*12
m5=["Jordan-Vogt-Roberts"]*12
m6=["Lasse-HallstrA-m"]*12

In [147]:
directordata["name"]=m1+m2+m3+m4+m5+m6

In [148]:
directordata.head()

,record,rank,value,name
0,Top Grossing Associate Producer at the Domesti...,886,"$30,038,362",D-J-Caruso
1,Top Grossing Director at the Domestic Box Offi...,228,"$341,032,453",D-J-Caruso
2,Top Grossing Executive Producer at the Domesti...,3005,"$8,087,783",D-J-Caruso
3,Top Grossing Producer at the Domestic Box Offi...,1771,"$28,607,015",D-J-Caruso
4,Top Grossing Screenwriter at the Domestic Box ...,2547,"$2,423,467",D-J-Caruso

In [149]:
'''output to csv file'''
directordata.to_csv('directordata.csv',index=False)

for overall analyzing about actor

In [55]:
def myfun2(url):
    '''this function is used for getting the data for specific study for actor'''
    url = "https://www.the-numbers.com/person/155860401-Donnie-Yen#tab=summary"
    res = requests.get(url)
    soup = BeautifulSoup(res.text, 'lxml')
    tables = soup.select('table')
    
    m=pd.read_html(tables[2].prettify())[0][1:]
    return m

In [57]:
a1=myfun2("https://www.the-numbers.com/person/39880401-Vin-Diesel#tab=summary")
a2=myfun2("https://www.the-numbers.com/person/155860401-Donnie-Yen#tab=summary")
a3=myfun2("https://www.the-numbers.com/person/22060401-Gerard-Butler")
a4=myfun2("https://www.the-numbers.com/person/1159650401-Talitha-Bateman")
a5=myfun2("https://www.the-numbers.com/person/39880401-Vin-Diesel")
a6=myfun2("https://www.the-numbers.com/person/72720401-Dwayne-Johnson")
a7=myfun2("https://www.the-numbers.com/person/540401-Tom-Cruise")
a8=myfun2("https://www.the-numbers.com/person/487260401-Annabelle-Wallis")
a9=myfun2("https://www.the-numbers.com/person/1650401-Mark-Wahlberg#tab=summary")
a10=myfun2("https://www.the-numbers.com/person/80850401-Shia-LaBeouf#tab=summary")
a11=myfun2("https://www.the-numbers.com/person/82280401-Brie-Larson#tab=summary")
a12=myfun2("https://www.the-numbers.com/person/670401-Samuel-L-Jackson#tab=summary")
a13=myfun2("https://www.the-numbers.com/person/11530401-Michael-Bay#tab=summary")
a14=myfun2("https://www.the-numbers.com/person/60610401-Lasse-HallstrA-m#tab=summary")

In [59]:
a1.columns=["item","rank","value"]
a2.columns=["item","rank","value"]
a3.columns=["item","rank","value"]
a4.columns=["item","rank","value"]
a5.columns=["item","rank","value"]
a6.columns=["item","rank","value"]
a7.columns=["item","rank","value"]
a8.columns=["item","rank","value"]
a9.columns=["item","rank","value"]
a10.columns=["item","rank","value"]
a11.columns=["item","rank","value"]
a12.columns=["item","rank","value"]
a13.columns=["item","rank","value"]
a14.columns=["item","rank","value"]

In [60]:
actordata=pd.concat([a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14])
actordata = actordata.reset_index()
actordata=actordata.drop('index',1)
actordata

                                                  item  rank           value
0    Top 100 Stars in Leading Roles at the Domestic...   246    $633,814,787
1    Top Stars at the Domestic Box Office (Rank 1,3...  1301    $803,934,812
2    Top 100 Stars in Leading Roles at the Internat...   139  $1,297,572,697
3    Top Stars at the International Box Office (Ran...   658  $1,602,975,782
4    Top 100 Stars in Leading Roles at the Worldwid...   173  $1,931,387,484
5    Top Stars at the Worldwide Box Office (Rank 80...   838  $2,406,910,594
6    Highest Grossing Stars of 2017 at the Domestic...    85             138
7    Highest Grossing Stars of 2018 at the Domestic...    61             138
8    Highest Grossing Stars of 2016 at the Internat...    33             160
9    Highest Grossing Stars of 2017 at the Internat...    17             236
10   Highest Grossing Stars of 2018 at the Internat...    26             169
11   Highest Grossing Stars of 2016 at the Worldwid...    48             151
12   Highest Grossing Stars of 2017 at the Worldwid...    23             225
13   Highest Grossing Stars of 2018 at the Worldwid...    27             173
14   Top Grossing Producer at the Domestic Box Offi...  7008          $7,679
15   Top Grossing Assistant Director at the Interna...   723     $25,040,000
16   Top Grossing Executive Producer at the Interna...  2170     $25,040,000
17   Top Grossing Assistant Director at the Worldwi...   907     $25,040,000
18   Top Grossing Executive Producer at the Worldwi...  2844     $25,040,000
19   Top Grossing Producer at the Worldwide Box Off...  7929          $7,679
20   Top 100 Stars in Leading Roles at the Domestic...   246    $633,814,787
21   Top Stars at the Domestic Box Office (Rank 1,3...  1301    $803,934,812
22   Top 100 Stars in Leading Roles at the Internat...   139  $1,297,572,697
23   Top Stars at the International Box Office (Ran...   658  $1,602,975,782
24   Top 100 Stars in Leading Roles at the Worldwid...   173  $1,931,387,484
25   Top Stars at the Worldwide Box Office (Rank 80...   838  $2,406,910,594
26   Highest Grossing Stars of 2017 at the Domestic...    85             138
27   Highest Grossing Stars of 2018 at the Domestic...    61             138
28   Highest Grossing Stars of 2016 at the Internat...    33             160
29   Highest Grossing Stars of 2017 at the Internat...    17             236
..                                                 ...   ...             ...
250  Highest Grossing Stars of 2018 at the Internat...    26             169
251  Highest Grossing Stars of 2016 at the Worldwid...    48             151
252  Highest Grossing Stars of 2017 at the Worldwid...    23             225
253  Highest Grossing Stars of 2018 at the Worldwid...    27             173
254  Top Grossing Producer at the Domestic Box Offi...  7008          $7,679
255  Top Grossing Assistant Director at the Interna...   723     $25,040,000
256  Top Grossing Executive Producer at the Interna...  2170     $25,040,000
257  Top Grossing Assistant Director at the Worldwi...   907     $25,040,000
258  Top Grossing Executive Producer at the Worldwi...  2844     $25,040,000
259  Top Grossing Producer at the Worldwide Box Off...  7929          $7,679
260  Top 100 Stars in Leading Roles at the Domestic...   246    $633,814,787
261  Top Stars at the Domestic Box Office (Rank 1,3...  1301    $803,934,812
262  Top 100 Stars in Leading Roles at the Internat...   139  $1,297,572,697
263  Top Stars at the International Box Office (Ran...   658  $1,602,975,782
264  Top 100 Stars in Leading Roles at the Worldwid...   173  $1,931,387,484
265  Top Stars at the Worldwide Box Office (Rank 80...   838  $2,406,910,594
266  Highest Grossing Stars of 2017 at the Domestic...    85             138
267  Highest Grossing Stars of 2018 at the Domestic...    61             138
268  Highest Grossing Stars of 2016 at the Internat...    33             160
269  Highest Grossing Stars of 2017 at the Internat...    17             236
270  Highest Grossing Stars of 2018 at the Internat...    26             169
271  Highest Grossing Stars of 2016 at the Worldwid...    48             151
272  Highest Grossing Stars of 2017 at the Worldwid...    23             225
273  Highest Grossing Stars of 2018 at the Worldwid...    27             173
274  Top Grossing Producer at the Domestic Box Offi...  7008          $7,679
275  Top Grossing Assistant Director at the Interna...   723     $25,040,000
276  Top Grossing Executive Producer at the Interna...  2170     $25,040,000
277  Top Grossing Assistant Director at the Worldwi...   907     $25,040,000
278  Top Grossing Executive Producer at the Worldwi...  2844     $25,040,000
279  Top Grossing Producer at the Worldwide Box Off...  7929          $7,679

[280 rows x 3 columns]

In [61]:
m1=["Vin-Diesel"]*20
m2=["Donnie-Yen"]*20
m3=["Gerard-Butler"]*20
m4=["Talitha-Bateman"]*20
m5=["Vin-Diesel"]*20
m6=["Dwayne-Johnson"]*20
m7=["Tom-Cruise"]*20
m8=["Annabelle-Wallis"]*20
m9=["Mark-Wahlberg"]*20
m10=["Shia-LaBeouf"]*20
m11=["Brie-Larson"]*20
m12=["Samuel-L-Jackson"]*20
m13=["Michael-Bay"]*20
m14=["Lasse-HallstrA-m"]*20
actordata["name"]=m1+m2+m3+m4+m5+m6+m7+m8+m9+m10+m11+m12+m13+m14

In [62]:
actordata.head()

,item,rank,value,name
0,Top 100 Stars in Leading Roles at the Domestic...,246,"$633,814,787",Vin-Diesel
1,"Top Stars at the Domestic Box Office (Rank 1,3...",1301,"$803,934,812",Vin-Diesel
2,Top 100 Stars in Leading Roles at the Internat...,139,"$1,297,572,697",Vin-Diesel
3,Top Stars at the International Box Office (Ran...,658,"$1,602,975,782",Vin-Diesel
4,Top 100 Stars in Leading Roles at the Worldwid...,173,"$1,931,387,484",Vin-Diesel

In [63]:
'''output to csv file'''
actordata.to_csv('actordata.csv',index=False)